networks:
  reverse-proxy:
  monitor:

volumes:
  elasticsearch-volume:

services:
  app:
    image: pcandido/full-stack/app
    container_name: app
    build: app
    volumes:
      - ./app/logs:/app/logs
    ports:
      - 8080:8080
    networks:
      - reverse-proxy

  nginx:
    image: pcandido/full-stack/nginx
    container_name: nginx
    build: nginx
    volumes:
      - ./nginx/config:/etc/nginx/conf.d
      - ./nginx/logs:/var/log/nginx
    ports:
      - 80:80
    networks:
      - reverse-proxy

  elasticsearch:
    image: pcandido/full-stack/elasticsearch
    container_name: elasticsearch
    build:
      context: elasticsearch
      args:
        ELK_VERSION: $ELK_VERSION
    volumes:
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
      - elasticsearch-volume:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - monitor

  kibana:
    image: pcandido/full-stack/kibana
    container_name: kibana
    build:
      context: kibana
      args:
        ELK_VERSION: $ELK_VERSION
    volumes:
      - ./kibana/config/kibana.yml:/usr/share/kibana/config/kibana.yml:ro
    ports:
      - 5601:5601
    networks:
      - monitor
    depends_on:
      elasticsearch:
        condition: service_healthy
