networks:
  reverse-proxy:

services:
  app:
    image: pcandido/full-stack/app
    container_name: app
    build: ./app
    volumes:
      - ./app/logs:/app/logs
    ports:
      - 8080:8080
    networks:
      - reverse-proxy

  nginx:
    image: pcandido/full-stack/nginx
    container_name: nginx
    build: ./nginx
    volumes:
      - ./nginx/config:/etc/nginx/conf.d
      - ./nginx/logs:/var/log/nginx
    ports:
      - 80:80
    networks:
      - reverse-proxy
    depends_on:
      app:
        condition: service_healthy
