apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    orgId: 1
    uid: prometheus
    url: http://prometheus:9090

  - name: Elasticsearch
    type: elasticsearch
    access: proxy
    orgId: 1
    uid: elasticsearch
    url: http://elasticsearch:9200
