scrape_configs:
  - job_name: node_exporter
    scrape_interval: 5s
    static_configs:
      - targets:
        - host.docker.internal:9100
  - job_name: nginx-vts
    scrape_interval: 5s
    metrics_path: /
    static_configs:
      - targets:
          - nginx-be:8882