filebeat.inputs:
  - type: log
    enabled: true
    paths:
      - /var/log/ui/access.log
      - /var/log/ui/error.log
      - /var/log/nginx/access.log
      - /var/log/nginx/error.log
      - /var/log/app/app.log

output.logstash:
  enabled: true
  hosts: ["logstash:5044"]

http:
  enabled: true
  port: 5067
  host: 0.0.0.0